import express from "express";
import { verifyToken } from "../utils/verifyUser.js";
import { create } from "../controllers/post.controller.js";
import { getPosts } from "../controllers/post.controller.js";
import { deletePost } from "../controllers/post.controller.js";
import { editPost } from "../controllers/post.controller.js";
const router = express.Router();
router.post("/create", verifyToken, create);
router.get("/getposts", getPosts);
router.delete("/deletePosts/:postId/:userId", verifyToken, deletePost);
router.put("/editPosts/:postId/:userId", verifyToken, editPost);
export default router;
